version: '3.8'
services:
  db:
    container_name: db
    hostname: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_DB=minca
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432
    expose:
      - 5432
  app:
    container_name: app-sm
    build: 
      context: .
      dockerfile: Dockerfile
    #command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    command: /app/startup.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://fastapi:123123@db/minca
    depends_on:
      - db
